[package]
name = "pacific"
version = "0.1.0"
edition = "2024"

[dependencies]
v4 = {git = "https://github.com/gamehunter101/v4-engine"}
nalgebra = "0.33.2"
wgpu = "28.0.0"
tokio = { version = "1.45.1", features = ["full"] }
bytemuck = "1.23.0"
image = "0.25.8"
async-trait = "0.1.89"
winit = "0.31.0-beta.2"
winit_input_helper = { git = "https://github.com/GameHunter101/winit_input_helper" }
